"""Generate the local .env with random credentials.

Nothing is printed and an existing file is never overwritten, so a secret can
neither leak into a terminal log nor be silently replaced. The same values
are used by the containers and by the application, which is why they live in
one generated file instead of being typed twice.
"""

import secrets
from pathlib import Path

target = Path(".env")
if target.exists():
    raise SystemExit(".env already exists; not overwritten")

target.write_text(
    "\n".join(
        [
            "# Generated by scripts/configure.py - do not commit this file.",
            f"POSTGRES_PASSWORD={secrets.token_hex(24)}",
            f"APP_DB_PASSWORD={secrets.token_hex(24)}",
            "",
            "# MinIO (S3-compatible object storage).",
            "# The access key must be at least 3 characters and the secret at least 8.",
            f"MINIO_ROOT_USER=activity4{secrets.token_hex(4)}",
            f"MINIO_ROOT_PASSWORD={secrets.token_hex(24)}",
            "",
        ]
    )
)
print("Created local credentials without displaying them.")
